### DISCUSSION TITLE
Modifications to Learnr User-Interface

### DISCUSSION THREAD

**Discussion by kgranillo10** [rstudio/learnr#716] [Q&A] [answered]
I have a few questions about the Learnr package, which I hope someone might be able to answer. Let me provide some context first. I recently have been using the Learnr package to conduct an experiment and obtain survey data. I understand that that was not the original intention of the package; however, it has really served well for this purpose. However, there are few things I would like to modify, and I could not seem to find any sources indicated if these modifications are possible. The following are the modification I would like to implement:

- Remove the Menu Bar displayed to the left of the interface.
- Remove the 'Run Code" button and only leave the "Submit Answer" button.
- Remove the option to continue to the next page without first submitting answers to the previous "survey items" (i.e., submitting answers to the exercises). 

I really would appreciate any help. Thank you for taking the time to respond to my inquiry!

**Comment by gadenbuie** [comment, marked as answer]
Thanks @kgranillo10! I'll answer each one individually:

### Remove the Menu Bar to the left of the interface

If you want to hide the navigation menu but still use learnr's content paging via the Continue button, you can use a little bit of CSS:

```css
.topicsList .nav {
	display: none;
}
```

Or to completely remove the sidebar and make the content panel "full-width", use these rules:

```css
.topicsContainer {
  display: none;
}

.topics {
  width: 100%;
}
```

### Remove the "Run Code" button and only leave the "Submit Answer" button

Similarly, you can use a small CSS rule to achieve this.

```css
.btn-tutorial-run:not(:last-child) {
	display: none;
}
```

This rule will actually only hide the "Run Code" button _if the "Submit Answer" button is present_. So if an exercise doesn't have a solution, the "Run Code" button will still show and users will always have a way to evaluate the code.

### Remove the option to continue to the next page without first submitting answers

You can use `progressive: true` and `allow_skip: false` in the options for [learnr::tutorial](https://rstudio.github.io/learnr/reference/tutorial.html) to achieve this (but just for exercises; there's [an open issue](https://github.com/rstudio/learnr/issues/505) to extend this to questions as well).

````markdown
---
output:
  learnr::tutorial:
    progressive: true
    allow_skip: false
runtime: shinyrmd
---
````

### How to include custom CSS

1. Create a file called `custom.css` (or something similar) in a `css/` folder next to your tutorial `.Rmd`.

1. Add those two rules to the CSS file:

   ```css
   /* css/custom.css */
   .topicsList .nav {
   	display: none;
   }
   
   .btn-tutorial-run:not(:last-child) {
   	display: none;
   }
   ```

1. Then tell learnr to use this CSS file in your YAML options:

   ```yaml
   output: 
     learnr::tutorial:
        css: css/custom.css
   ```

**Reply by kgranillo10** [reply]
Thank you so much for the reply! Quick question: where would I add the CSS commands?

**Reply by kgranillo10** [reply]
Actually, figured it out! However, I tried using the .topicsList .nav code and it doesn't appear to remove the left navigation pane. The "submit answer" only option did work.

**Reply by kgranillo10** [reply]
![image](https://user-images.githubusercontent.com/89270977/182176393-a3bbe8ae-90b0-44f1-a562-f8945936a4e8.png)

**Reply by gadenbuie** [reply]
Good question! I meant to include that in my answer 😄 

1. Create a file called `custom.css` (or something similar) in a `www/` folder next to your tutorial `.Rmd`.

1. Add those two rules to the CSS file:

   ```css
   /* www/custom.css */
   .topicsList .nav {
   	display: none;
   }
   
   .btn-tutorial-run:not(:last-child) {
   	display: none;
   }
   ```

1. Then tell learnr to use this CSS file in your YAML options:

   ```yaml
   output: 
     learnr::tutorial:
        css: www/custom.css
   ```

**Reply by gadenbuie** [reply]
> Actually, figured it out! However, I tried using the .topicsList .nav code and it doesn't appear to remove the left navigation pane. The "submit answer" only option did work.

Yeah, I think you may run into some weird behavior if you completely remove the left panel. But you could try this and see if it works for you:

```css
.topicsContainer {
  display: none;
}

.topics {
  width: 100%;
}
```
