### ISSUE TITLE
Is there a way to hide menu on left?

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#160]
I realize I can zoom until things are so big that the left-hand menu goes a way, but I'd like to be able to hide that menu or force it to the top without making things so large.  Is this possible?

**Comment by rpruim** [comment]
Been fighting this again at workshops this week and last.  Would love to be able to disable the menu of the left without making the font so large.

**Comment by annafergusson** [comment]
Just in case you haven't found a solution yet Randy @rpruim, if you steal the last chunk of css from the learnr tutorial template, increase the max-width to something crazy like 4000, and add this to your own css file, you will get what you want :-)

Examples....

Add reference to your style sheet ...

```r
output:
  learnr::tutorial:
    progressive: true
    css: css/style.css
```

Add this to style.css ....
```css
@media screen and (max-width: 4000px) {
  .topics {
    width: 99%;
  }

  .topics .tutorialTitle {
    display: block;
    cursor: pointer;
  }

  .topicsContainer {
    width: 1%;
    min-width: 1px;
    margin-right: 0;
  }

  .topicsList {
    padding: 0px 10px 20px 1%;
    background-color: rgba(255, 255, 255, 0.98);

    box-shadow: 0 5px 25px 0px rgba(0, 0, 0, 0.15);
    -webkit-box-shadow: 0 5px 25px 0px rgba(0, 0, 0, 0.15);
  }

  .topicsList.hideFloating {
    display: none;
  }

  .paneCloser {
    display: inline-block;
  }
}
```
