### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by kellobri** [rstudio/learnr#245]
Would it be possible to include a custom favicon for learnr through the `www/favicon.ico` directory, such as for a shiny application?

Of note: The standard "header includes" pattern works for regular Rmd and `runtime: shiny` but not for `runtime: shiny_prerendered` _(documents published to an RStudio Connect server)_

- Successful:
```
---
title: "Shiny Runtime Favicon Test"
output: 
  html_document:
    includes:
      in_header: "favicon.html"
runtime: shiny
---
```

- Unsuccessful:
```
---
title: "Learnr Favicon Test"
output: 
  learnr::tutorial:
    includes:
      in_header: "favicon.html"
runtime: shiny_prerendered
---
```

**Comment by siegerts** [comment]
After following a similar approach as yours, I saw that the html is injected into a 'duplicate' `<head>` in the DOM since the _prerendered_ contents occupy the initial `<head>` structure.

A workaround is to pop the html fragment into the `after_body` _include_ and then dynamically add the favicon link into that first instance of `<head>`. 

This is not my favorite but seems to work as expected. Can also be adjusted for the specifics of different browsers, if needed.

```yaml
---
title: "Test Page"
output: 
  learnr::tutorial:
    includes:
      after_body: ./www/favicon.html
runtime: shiny_prerendered
---
```


```html
<script type="text/javascript">
  (function() {
    var link = document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = '/www/favicon.ico';
    document.getElementsByTagName('head')[0].appendChild(link);
})();
</script>
```
