### ISSUE TITLE
Anchor sections in rmarkdown 2.5 with learnr

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/learnr#446]
rmarkdown 2.5 introduced a new anchor sections feature that adds `#` characters when hovering over heading text. Unfortunately, there are a few places where this feature impacts learnr tutorials.

1. **Tabsets**. Because tabsets are initialized _after_ the anchor sections JS is run, anchors are added to the tab headings. They overflow the tab container and add vertical space between the tabs and the content.

   The easy fix would be to hide the anchors in the tabset styles in the tutorial template.

   ```css
   .tabset > ul.nav-tabs > li > .anchor-section {
     display: none;
   }
   ```

   I can PR this if this works. Otherwise, the alternative would be to ensure that tabs are initialized before anchors are added.

1. Empty headings used to add pauses, like the empty level-3 headings often used in tutorials, end up with an anchor even though there's no text. This may be fixed upstream https://github.com/rstudio/rmarkdown/issues/1937

1. As far as I can tell, it's not possible to link into a level-3 heading or below using URL hashes. This makes sense, since those sections may not be revealed until a user has worked through some exercises first. For this reason, in addition to the above, it may make sense to disable `anchor_sections` by default for learnr tutorials. I can also PR this change if desired.

**Comment by gadenbuie** [comment]
Update: I included the CSS fix for tabsets in learnr in the PR to fix empty headings in rmarkdown, since there are likely other places in the rmdverse where that problem may arise.

To address the third point, the following CSS could be added to learnr, effectively limiting section anchors to the level 2 headings.

```css
h3 > .anchor-section,
h4 > .anchor-section,
h5 > .anchor-section,
h6 > .anchor-section {
  display: none;
}
```
