### ISSUE TITLE
Error when multiple Rmarkdown files

### ISSUE THREAD

**Issue by johnbde** [rstudio/learnr#510]
Thanks for this great package. When I am trying to add navigation bar with link to multiple Rmd files in `_site.yml` file. It shows below error when running `rmarkdown::render_site()`:
```
Error in rmarkdown::html_document(smart = smart, theme = theme, lib_dir = NULL,  : 
  formal argument "lib_dir" matched by multiple actual arguments

```

**_site.yml **

```
name: "my-website"
title: "Tutorial"
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output: 
  learnr::tutorial            
runtime: shiny_prerendered
```

I am using version learnr_0.10.1.9008.

index.Rmd and about.Rmd are demo templates of learnr
