### ISSUE TITLE
Is it possible to configure learnr to always forget previous attempts

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/learnr#607]
Just got around to using `learnr` + `gradethis` for a randomization experiment.
If i'm reading this correctly,
It seems this PR will fix the issue I'm having with my local `.Rmd` document (not as a package) and on shinyapps.io where my previous attempts are being cached, and I either need to manually "Start Over" or run things in a private/incognito window.  👍 

Will this let me also put in the yaml header so that it never caches the previous attempts? Something like:

```
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
    clean: true # <--- this option?
```

_Originally posted by @chendaniely in https://github.com/rstudio/learnr/issues/601#issuecomment-961222821_
