### ISSUE TITLE
Document that setting tutorial ID is required on RStudio Cloud

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/learnr#656]
From [RStudio Community](https://community.rstudio.com/t/learnr-tutorials-not-saving-in-rstudio-cloud/128320):

> Some students are not able to install the tutorial package onto their computer, so I setup a Rstudio cloud project for them to use. However when they stop the session after they work on it for a little bit (to save computational time and stay under the free time limits), it does not save their work. 
> Is this a bug?

The tutorial progress storage is based on the tutorial's ID. If your [tutorial doesn't explicitly set the ID](https://rstudio.github.io/learnr/articles/publishing.html#tutorial-identifiers), then a default value is chosen based on a few things. On RStudio Cloud, the port of the application path encoded in the URL where the user accesses the running tutorial. learnr will encorporate that port in the default tutorial identifier, but unfortunately this port number changes with each run.

Adding the following to the YAML frontmatter of those tutorials this will clear up problems for your users, even on RStudio Cloud:

```yaml
tutorial:
  id: math350_lrt_1_introR
  version: 1 # change the version when you want to invalidate past progress
```

Note that if you release a totally different version of the tutorial and want any one with stored progress to reset, you can change the version value (which can be an arbitrary string).

**Comment by norcalbiostat** [comment]
Adding the id and reinstalling the tutorial in the cloud project did not resolve the issue.

**Comment by gadenbuie** [comment]
That's unfortunate. Is the package with the tutorials available online and if so can you please share the repo URL? Can you also please share the output from `devtools::session_info()`?

**Comment by gadenbuie** [comment]
oh wait, instead of

```yaml
output: 
    learnr::tutorial:
      progressive: true
      allow_skip: true
      id: math350_lrt_1_introR
      version: 1 # change the version when you want to invalidate past progress
```

please try

```yaml
output: 
    learnr::tutorial:
      progressive: true
      allow_skip: true
tutorial:
      id: math350_lrt_1_introR
      version: 1 # change the version when you want to invalidate past progress
```
