### ISSUE TITLE
Can someone tell me how i can change the name of "Next topic" button? i would very much appreciate it

### ISSUE THREAD

**Issue by themfrees** [rstudio/learnr#669]
![Screenshot 2022-03-05 at 13 46 04](https://user-images.githubusercontent.com/100830178/156883646-d92f1194-51cc-4d33-9726-c333df3e7337.png)

**Comment by gadenbuie** [comment]
Have you seen the [Internationalization vignette](https://rstudio.github.io/learnr/articles/multilang.html)?

**Comment by themfrees** [comment]
Thanks you, but i tried that and somehow it doesnt work, here is screenshot of my code, like i said even if i run the document nothing changes.
![Screenshot 2022-03-05 at 21 13 00](https://user-images.githubusercontent.com/100830178/156898615-78830e75-0a0c-4097-8b1f-b78443d0e416.png)

**Comment by gadenbuie** [comment]
Try putting the `button` key under `learnr::tutorial` > `language` > _your language_. E.g.

```yaml
output: 
  learnr::tutorial:
    language: en
      button:
        nexttopic: starten
```

But you might also want to try out the built-in German language translations:

```yaml
output: 
  learnr::tutorial:
    language: de
```
