### ISSUE TITLE
Sage cell works on local server but not on web server

### ISSUE THREAD

**Issue by acarzfr** [rstudio/learnr#671]
Hello. I am making a tutorial using sage cell. Although the sage cell works on the local server, it does not work at https://acarzfr.shinyapps.io/asal_sayilar/.

Local server screenshot:

![image](https://user-images.githubusercontent.com/45861141/157126955-fbdea248-a903-4369-9753-7e7b30b09c83.png)

What could the problem be caused by?

**Comment by gadenbuie** [comment]
I don't really know. If you open the developer console of your browser, you may see some messages with more information (right click on the page and select "Inspect Element"). For example, I see that the sagecell web dependencies were blocked:

```
Blocked loading mixed active content “http://aleph.sagemath.org/static/jquery.min.js” asal_sayilar
Blocked loading mixed active content “http://aleph.sagemath.org/static/embedded_sagecell.js” asal_sayilar
Uncaught ReferenceError: sagecell is not defined
    <anonymous> https://acarzfr.shinyapps.io/asal_sayilar/:49
asal_sayilar:49:5
```

MDN has some resources on [Mixed content - Web security | MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#mixed_active_content) that might be useful.

If you'd like to post a reproducible example, there's a better chance that I (or someone else) might be able to help you.

**Comment by acarzfr** [comment]
Head of `asal_sayilar.Rmd` file:
```
---
title: "Asal Sayılar"
output:
  learnr::tutorial:
    theme: "default"  #default,cerulean,cosmo,darkly,flatly,paper,readable,sandstone,simplex,spacelab,united,yeti
    includes:
      in_header: preamble.html
    progressive: true
    language: 
        tr:
          text:
            startover: Baştan Başlayın
            
runtime: shiny_prerendered
---
```
and the contents of the `preamble.html` file:

```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<script src="http://aleph.sagemath.org/static/jquery.min.js"></script>
<script src="http://aleph.sagemath.org/static/embedded_sagecell.js"></script>

<script>
    // Make the div with id 'mycell' a Sage cell
    sagecell.makeSagecell({inputLocation:  'div.m_sage',
                           linked: true,
                           template: sagecell.templates.minimal,
                           evalButtonText: "Sage"});
                           
    // Make *any* div with class 'compute' a Sage cell
    sagecell.makeSagecell({inputLocation: 'div.sage',
                           linked: true,
                           evalButtonText: "Sage",
                           hide: ["fullScreen", "permalink"],
                 //        languages: ["sage", "r"],
    
    });
    
    // Make *any* div with class 'compute' a Sage cell
    sagecell.makeSagecell({inputLocation: 'div.o_sage',
                           linked: true,
                           autoeval: true,
                       //    evalButtonText: "Sage",
                           hide: ["fullScreen", "permalink","editor","evalButton"],
                 //        languages: ["sage", "r"],
    
    });
</script>
```

The contents of the sage cell are:

```
<div class="o_sage"><script type="text/x-sage">
@interact
def _(aralık=range_slider(2,100,1,(2,12))):
      b=aralık[0]
      c=aralık[1]
      d=len(prime_range(b,c))
      show(prime_range(b,c))
</script>
</div>
```

I think the problem is that http://aleph.sagemath.org/static/jquery.min.js and http://aleph.sagemath.org/static/embedded_sagecell.js start with 'http' instead of 'https'.
